using UnityEditor;
using UnityEngine;
using System;
using System.Collections.Generic;
using PuzzleGame.Domain.Models;
using PuzzleGame.Application.Configuration;

namespace PuzzleGame.Editor
{
    public class LevelUITab : IEditorTab
    {
        public string TabName => "Level UI";
        private ForgeEditorWindow _window;

        private LevelData _selectedLevelForUI;
        private Vector2 _levelUIScroll;
        private int _selectedMoldIndex = -1;
        private string _newMoldColorHex = "#FF0000";
        private float _newMoldLayerAmount = 0.25f;

        public void OnEnable(ForgeEditorWindow window)
        {
            _window = window;
        }

        public void OnDisable()
        {
        }

        public void OnGUI()
        {
            EditorGUILayout.LabelField("Pre-built Level Designer", EditorStyles.boldLabel);
            EditorGUILayout.Space(4);

            EditorGUILayout.HelpBox(
                "Manual (non-autogenerated) level designer and editor.\n" +
                "Select a level, manage molds, and build layers visually.",
                MessageType.Info);

            EditorGUILayout.Space(4);

            // ── Level Selection ─────────────────────────────────────────────
            using (new EditorGUILayout.VerticalScope(EditorStyles.helpBox))
            {
                EditorGUILayout.LabelField("Select Level to Edit", EditorStyles.miniBoldLabel);

                var levels = AssetDatabase.FindAssets("t:LevelData", new[] { LevelDataBatchCreator.LevelPath });
                var levelOptions = new List<string> { "-- Select Level --" };
                var levelPaths = new List<string> { null };

                foreach (var guid in levels)
                {
                    string path = AssetDatabase.GUIDToAssetPath(guid);
                    var level = AssetDatabase.LoadAssetAtPath<LevelData>(path);
                    if (level != null)
                    {
                        string mode = level.autoGenerate ? "[Auto]" : "[Manual]";
                        levelOptions.Add($"Level {level.levelNumber} - {level.difficulty} {mode}");
                        levelPaths.Add(path);
                    }
                }

                int currentIndex = _selectedLevelForUI != null ? 
                    levelPaths.FindIndex(p => p != null && AssetDatabase.GetAssetPath(_selectedLevelForUI).Contains(p)) : 0;
                
                EditorGUILayout.Space(4);
                int selected = EditorGUILayout.Popup("Level", currentIndex, levelOptions.ToArray());
                
                if (selected >= 0 && selected < levelPaths.Count)
                {
                    if (selected != currentIndex)
                    {
                        _selectedLevelForUI = selected > 0 ? 
                            AssetDatabase.LoadAssetAtPath<LevelData>(levelPaths[selected]) : null;
                        _selectedMoldIndex = -1;
                    }
                }

                if (_selectedLevelForUI != null)
                {
                    EditorGUILayout.Space(4);
                    using (new EditorGUILayout.HorizontalScope())
                    {
                        EditorGUILayout.LabelField("Mode:", GUILayout.Width(50));
                        EditorGUILayout.LabelField(
                            _selectedLevelForUI.autoGenerate ? "Auto-Generated" : "Manual (Pre-built)",
                            _selectedLevelForUI.autoGenerate ? EditorStyles.boldLabel : EditorStyles.miniBoldLabel);
                    }
                }
            }

            if (_selectedLevelForUI == null)
            {
                EditorGUILayout.HelpBox("Please select a level to edit.", MessageType.Warning);
                return;
            }

            if (_selectedLevelForUI.autoGenerate)
            {
                EditorGUILayout.HelpBox(
                    "This level is in Auto-Generated mode. To edit manually, disable Auto-Generate.\n" +
                    "Click the button below to convert it to Manual mode.",
                    MessageType.Warning);

                if (GUILayout.Button("Convert to Manual Mode"))
                {
                    Undo.RecordObject(_selectedLevelForUI, "Convert to Manual");
                    _selectedLevelForUI.autoGenerate = false;
                    _selectedLevelForUI.Molds = GenerateDefaultMolds(_selectedLevelForUI);
                    EditorUtility.SetDirty(_selectedLevelForUI);
                    _window.SetStatus("Level converted to Manual mode.", MessageType.Info);
                }
                return;
            }

            EditorGUILayout.Space(4);
            _levelUIScroll = EditorGUILayout.BeginScrollView(_levelUIScroll);

            DrawMoldManagement();

            EditorGUILayout.EndScrollView();

            EditorGUILayout.Space(8);
            using (new EditorGUILayout.HorizontalScope())
            {
                if (GUILayout.Button("Save Changes", GUILayout.Height(28)))
                {
                    Undo.RecordObject(_selectedLevelForUI, "Save Level UI");
                    EditorUtility.SetDirty(_selectedLevelForUI);
                    AssetDatabase.SaveAssets();
                    _window.SetStatus("Level UI saved!", MessageType.Info);
                }
            }
        }

        public void OnSceneGUI(SceneView sceneView)
        {
        }

        private void DrawMoldManagement()
        {
            using (new EditorGUILayout.VerticalScope(EditorStyles.helpBox))
            {
                EditorGUILayout.LabelField("Mold Management", EditorStyles.miniBoldLabel);
                EditorGUILayout.Space(4);

                if (_selectedLevelForUI.Molds == null)
                    _selectedLevelForUI.Molds = new List<LevelMoldData>();

                EditorGUILayout.LabelField($"Molds: {_selectedLevelForUI.Molds.Count}", EditorStyles.miniBoldLabel);

                for (int i = 0; i < _selectedLevelForUI.Molds.Count; i++)
                {
                    var Mold = _selectedLevelForUI.Molds[i];
                    bool isSelected = _selectedMoldIndex == i;

                    using (new EditorGUILayout.HorizontalScope(EditorStyles.helpBox))
                    {
                        string label = Mold.isEmpty ? $"Mold {i + 1} [EMPTY]" : $"Mold {i + 1} ({Mold.layers.Count} layers)";
                        if (GUILayout.Toggle(isSelected, label, EditorStyles.radioButton, GUILayout.Width(200)))
                        {
                            _selectedMoldIndex = i;
                        }

                        GUILayout.FlexibleSpace();

                        bool newEmpty = EditorGUILayout.Toggle("Empty", Mold.isEmpty, GUILayout.Width(80));
                        if (newEmpty != Mold.isEmpty)
                        {
                            Undo.RecordObject(_selectedLevelForUI, "Toggle Mold Empty");
                            Mold.isEmpty = newEmpty;
                            if (newEmpty) Mold.layers.Clear();
                        }

                        if (GUILayout.Button("X", GUILayout.Width(25)))
                        {
                            Undo.RecordObject(_selectedLevelForUI, "Delete Mold");
                            _selectedLevelForUI.Molds.RemoveAt(i);
                            if (_selectedMoldIndex >= _selectedLevelForUI.Molds.Count)
                                _selectedMoldIndex = _selectedLevelForUI.Molds.Count - 1;
                            i--;
                        }
                    }
                }

                EditorGUILayout.Space(4);
                using (new EditorGUILayout.HorizontalScope())
                {
                    if (GUILayout.Button("+ Add Filled Mold"))
                    {
                        Undo.RecordObject(_selectedLevelForUI, "Add Mold");
                        Color c1 = SceneBuilder.DefaultPalette[UnityEngine.Random.Range(0, SceneBuilder.DefaultPalette.Length)];
                        Color c2 = SceneBuilder.DefaultPalette[(UnityEngine.Random.Range(1, SceneBuilder.DefaultPalette.Length) + 1) % SceneBuilder.DefaultPalette.Length];
                        var newMold = new LevelMoldData
                        {
                            isEmpty = false,
                            layers = new List<LevelLayerData>
                            {
                                new LevelLayerData { color = c1, amount = 0.25f },
                                new LevelLayerData { color = c1, amount = 0.25f },
                                new LevelLayerData { color = c2, amount = 0.25f },
                                new LevelLayerData { color = c2, amount = 0.25f }
                            }
                        };
                        _selectedLevelForUI.Molds.Add(newMold);
                        _selectedMoldIndex = _selectedLevelForUI.Molds.Count - 1;
                    }

                    if (GUILayout.Button("+ Add Empty Mold"))
                    {
                        Undo.RecordObject(_selectedLevelForUI, "Add Empty Mold");
                        var newMold = new LevelMoldData
                        {
                            isEmpty = true,
                            layers = new List<LevelLayerData>()
                        };
                        _selectedLevelForUI.Molds.Add(newMold);
                        _selectedMoldIndex = _selectedLevelForUI.Molds.Count - 1;
                    }
                }

                if (_selectedMoldIndex >= 0 && _selectedMoldIndex < _selectedLevelForUI.Molds.Count)
                {
                    var selectedMold = _selectedLevelForUI.Molds[_selectedMoldIndex];
                    EditorGUILayout.Space(8);
                    DrawLayerEditor(selectedMold);
                }
            }
        }

        private void DrawLayerEditor(LevelMoldData Mold)
        {
            using (new EditorGUILayout.VerticalScope(EditorStyles.helpBox))
            {
                EditorGUILayout.LabelField($"Mold {_selectedMoldIndex + 1} - Layer Editor", EditorStyles.miniBoldLabel);
                EditorGUILayout.Space(4);

                if (Mold.isEmpty)
                {
                    EditorGUILayout.HelpBox("Cannot add layers to an empty mold.", MessageType.Info);
                    return;
                }

                if (Mold.layers == null)
                    Mold.layers = new List<LevelLayerData>();

                EditorGUILayout.LabelField($"Layers: {Mold.layers.Count}", EditorStyles.miniBoldLabel);

                for (int i = 0; i < Mold.layers.Count; i++)
                {
                    var layer = Mold.layers[i];
                    
                    using (new EditorGUILayout.HorizontalScope())
                    {
                        int displayNum = Mold.layers.Count - i;
                        EditorGUILayout.LabelField($"#{displayNum}", GUILayout.Width(30));

                        layer.color = EditorGUILayout.ColorField(layer.color, GUILayout.Width(80));

                        EditorGUILayout.LabelField("Amount:", GUILayout.Width(60));
                        layer.amount = EditorGUILayout.Slider(layer.amount, 0.05f, 1f, GUILayout.Width(120));

                        var rect = GUILayoutUtility.GetRect(20, 20);
                        EditorGUI.DrawRect(rect, layer.color);

                        GUILayout.FlexibleSpace();

                        if (GUILayout.Button("X", GUILayout.Width(25)))
                        {
                            Undo.RecordObject(_selectedLevelForUI, "Delete Layer");
                            Mold.layers.RemoveAt(i);
                            i--;
                        }

                        if (i > 0 && GUILayout.Button("▲", GUILayout.Width(25)))
                        {
                            Undo.RecordObject(_selectedLevelForUI, "Move Layer Up");
                            var temp = Mold.layers[i];
                            Mold.layers[i] = Mold.layers[i - 1];
                            Mold.layers[i - 1] = temp;
                        }
                        if (i < Mold.layers.Count - 1 && GUILayout.Button("▼", GUILayout.Width(25)))
                        {
                            Undo.RecordObject(_selectedLevelForUI, "Move Layer Down");
                            var temp = Mold.layers[i];
                            Mold.layers[i] = Mold.layers[i + 1];
                            Mold.layers[i + 1] = temp;
                        }
                    }
                }

                EditorGUILayout.Space(4);

                EditorGUILayout.LabelField("Add New Layer", EditorStyles.miniBoldLabel);
                using (new EditorGUILayout.HorizontalScope())
                {
                    _newMoldColorHex = EditorGUILayout.TextField("Color Hex", _newMoldColorHex, GUILayout.Width(150));
                    
                    Color parsedColor;
                    if (ColorUtility.TryParseHtmlString(_newMoldColorHex, out parsedColor))
                    {
                        var rect = GUILayoutUtility.GetRect(20, 20);
                        EditorGUI.DrawRect(rect, parsedColor);
                    }

                    _newMoldLayerAmount = EditorGUILayout.Slider("Amount", _newMoldLayerAmount, 0.05f, 1f, GUILayout.Width(150));

                    if (GUILayout.Button("Add Layer", GUILayout.Width(100)))
                    {
                        Color newColor;
                        if (ColorUtility.TryParseHtmlString(_newMoldColorHex, out newColor))
                        {
                            Undo.RecordObject(_selectedLevelForUI, "Add Layer");
                            Mold.layers.Add(new LevelLayerData { color = newColor, amount = _newMoldLayerAmount });
                        }
                    }
                }

                EditorGUILayout.Space(4);
                EditorGUILayout.LabelField("Quick Add:", EditorStyles.miniBoldLabel);
                using (new EditorGUILayout.HorizontalScope())
                {
                    if (GUILayout.Button("Red")) AddQuickColor(Mold, Color.red);
                    if (GUILayout.Button("Blue")) AddQuickColor(Mold, Color.blue);
                    if (GUILayout.Button("Green")) AddQuickColor(Mold, Color.green);
                    if (GUILayout.Button("Yellow")) AddQuickColor(Mold, Color.yellow);
                }
            }
        }

        private void AddQuickColor(LevelMoldData Mold, Color color)
        {
            Undo.RecordObject(_selectedLevelForUI, "Add Quick Color");
            if (Mold.layers == null) Mold.layers = new List<LevelLayerData>();
            Mold.layers.Add(new LevelLayerData { color = color, amount = 0.25f });
        }

        private List<LevelMoldData> GenerateDefaultMolds(LevelData level)
        {
            var Molds = new List<LevelMoldData>();
            int colorsPerMold = level.maxLayersPerMold / 2;
            
            Color[] defaultColors = new Color[] { Color.red, Color.blue, Color.green, Color.yellow };

            for (int i = 0; i < level.colorCount; i++)
            {
                var Mold = new LevelMoldData
                {
                    isEmpty = false,
                    layers = new List<LevelLayerData>()
                };

                Color color = defaultColors[i % defaultColors.Length];
                for (int j = 0; j < colorsPerMold; j++)
                {
                    Mold.layers.Add(new LevelLayerData { color = color, amount = 0.25f });
                }

                Molds.Add(Mold);
            }

            for (int i = 0; i < level.emptyMoldCount; i++)
            {
                Molds.Add(new LevelMoldData
                {
                    isEmpty = true,
                    layers = new List<LevelLayerData>()
                });
            }

            return Molds;
        }
    }
}
